name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Docker Image
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write

  deploy:
    name: Deploy to VPS
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets:
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_PATH: ${{ secrets.VPS_PATH }}
